### ISSUE TITLE
FileNotFoundError: File b'training_samples_X4_1Y.csv' does not exist

### ISSUE THREAD

**Issue by zy486at189cn** [nabimaru/RadarNet#5]
First ,it is a great job!

When I train the model, "python3 train.py -arch scd -b 512 -e 300 -op Adam" . The result is "FileNotFoundError: File b'training_samples_X4_1Y.csv' does not exist". Where can I download the file "samples_X4_1Y.csv"?  Where can I download the dataset? Thanks!

**Comment by nabilbenmerad** [comment]
Hey, thank you! We're sorry for the lacking file, I added it and made sure the training goes as expected.
Let us know how it goes!

PS : The default batch size gives good results but you could reduce it if you don't have enough memory.
