### ISSUE TITLE
What means is the the train data format? 

### ISSUE THREAD

**Issue by zy486at189cn** [nabimaru/RadarNet#6]
@nabimaru @nfsrules  Nice job!
I have success to run the project.But I wonder what means of the train data ,and the data format?
such as the datasets.py:
x_train = np.zeros((908,4,64,64), dtype=np.float32) # (908,1)
y_train = np.zeros((908,1,64,64), dtype=np.float32) # (908,1)

What are the x_train and y_train ?
The x_train is four optical flow pictures(every five minute)?
The y_train is the next five minute optical flow picture?

Could you tell me ?Are there papers about the project?Thank you!

**Comment by zy486at189cn** [comment]
@nabimaru @nfsrules 
May I get some... thanks

**Comment by nabilbenmerad** [comment]
Hey,
We built time sequences composed by 4 past radar maps input and 1 future map as target. The size of each map is (64 x 64)
So the input that consists of the 4 past maps are fed to the soft conv-deconv neural network to produce the motion field which is a two dimensional vector that describes how the current map will be transformed to reach the map to be predicted (5 minutes forecast).

Here's the paper showing more details about the approach : https://arxiv.org/pdf/1711.07970.pdf

Hope this helps.

**Comment by zy486at189cn** [comment]
Thanks！
